name: app_user
description: "Lifestyle related diseases"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 2.2.3
  cupertino_icons: 1.0.6
  get_it: 7.7.0
  easy_localization: 3.0.6
  flutter_secure_storage: 9.0.0
  json_annotation: 4.9.0
  injectable: 2.4.1
  flutter_gen: 5.4.0
  flutter_bloc: 8.1.5
  bloc: 8.1.4
  go_router: 14.0.2
  dio: 5.4.3+1
  fpdart: ^1.1.0
  freezed_annotation: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.0
  injectable_generator: 2.6.1
  build_runner: 2.4.9
  flutter_gen_runner: 5.4.0
  freezed: 2.5.2

flutter_gen:
  output: lib/src/core/assets/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets
      package_parameter_enabled: false
    enabled: true
  fonts:
    outputs:
      class_name: AppFonts
    enabled: true
  line_length: 80

flutter:
  uses-material-design: true

  
